import {render, screen, fireEvent, waitFor, cleanup} from '@testing-library/react';
import {afterEach, describe, expect, it, vi} from 'vitest';
import Corporate from './Corporate';
const session={user:{id:'owner',display_name:'Owner',role:'admin'},csrf_token:'synthetic-csrf'};
const work={id:'work-1',title:'Synthetic task',objective:'Local change',acceptance:'Tests pass',digest:'a'.repeat(64)};
const snapshot:{projects:{id:string;name:string;repository_name:string}[];work:typeof work[];approvals:{work_id:string;expires_at:string}[];jobs:unknown[];audit:unknown[];costs:{limit_cents:number;reserved_cents:number;actual_cents:number;actuals:unknown[]};connections:{mode:string;live_dispatch:string;repository:{name:string}}}={projects:[{id:'project-1',name:'Local Project',repository_name:'astro-dev-lab/me-fastapi'}],work:[work],approvals:[],jobs:[],audit:[],costs:{limit_cents:0,reserved_cents:0,actual_cents:0,actuals:[]},connections:{mode:'contract',live_dispatch:'BLOCKED_UPSTREAM_AUTHORIZATION',repository:{name:'astro-dev-lab/me-fastapi'}}};
function mock(production=true, supplied=snapshot){const requests: {path:string,body:unknown}[]=[];vi.stubGlobal('fetch',vi.fn(async(path:string,options?:RequestInit)=>{requests.push({path,body:options?.body?JSON.parse(String(options.body)):null});const data=path==='/api/auth/config'?{mode:production?'production':'simulation',credential_login:production}:path==='/api/auth/me'?session:path==='/api/corporate/snapshot'?supplied:{};return {ok:true,status:200,json:async()=>data};}));return requests;}
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('Corporate',()=>{
 it('has exactly six sections, truthful blocked connections and separate demo',async()=>{mock();render(<Corporate/>);await screen.findByRole('button',{name:'Projects'});expect(screen.getAllByRole('navigation')[0].querySelectorAll('button')).toHaveLength(6);fireEvent.click(screen.getByRole('button',{name:'Connections'}));expect(screen.getByText(/BLOCKED_UPSTREAM_AUTHORIZATION/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open separate demo'}).getAttribute('href')).toBe('/');});
 it('requires a deliberate checkbox before a distinct audited approval request',async()=>{const requests=mock();render(<Corporate/>);fireEvent.click(await screen.findByRole('button',{name:'Review/Approve'}));const button=screen.getByRole('button',{name:'Approve zero-cost contract'});expect(button).toHaveProperty('disabled',true);expect(requests.some(x=>x.path.includes('/approve'))).toBe(false);fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(button);await waitFor(()=>expect(requests.some(x=>x.path==='/api/corporate/work/work-1/approve')).toBe(true));expect(requests.find(x=>x.path.endsWith('/approve'))?.body).toEqual({digest:work.digest,confirmation:'APPROVE_ZERO_COST_CONTRACT'});});
 it('does not expose Corporate via demo auto-login',async()=>{const requests=mock(false);render(<Corporate/>);await screen.findByText(/Corporate requires provisioned credential authentication/);expect(requests.some(x=>x.path.includes('demo-login')||x.path.includes('corporate/snapshot'))).toBe(false);});
 it('expired approvals require fresh intake and offer no contract action',async()=>{mock(true,{...snapshot,approvals:[{work_id:work.id,expires_at:'2000-01-01T00:00:00Z'}]} as typeof snapshot);render(<Corporate/>);fireEvent.click(await screen.findByRole('button',{name:'Review/Approve'}));expect(screen.getByText(/Approval expired. Submit a new intake/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Jobs'}));expect(screen.queryByRole('button',{name:'Prepare zero-cost contract'})).toBeNull();});
 it('shows zero G2 budget without referencing P1 funds',async()=>{mock();render(<Corporate/>);fireEvent.click(await screen.findByRole('button',{name:'Costs'}));expect(screen.getByText(/Incremental budget: \$0.00/)).toBeTruthy();expect(screen.queryByText(/200/)).toBeNull();});
});
