import {useEffect, useState} from 'react';
import {api, ApiError, type Session} from './api';
import './corporate.css';
type Project={id:string;name:string;repository_name:string};
type Work={id:string;title:string;objective:string;acceptance:string;digest:string};
type Approval={work_id:string;expires_at:string};
type Job={id:string;work_id:string;status:string;issue_reference:string};
type Snapshot={projects:Project[];work:Work[];approvals:Approval[];jobs:Job[];audit:{id:number;event:string;created_at:string}[];costs:{limit_cents:number;reserved_cents:number;actual_cents:number;actuals:{job_id:string;reference:string}[]};connections:{mode:string;live_dispatch:string;repository:{name:string}}};
const sections=['Projects','New Work','Jobs','Review/Approve','Costs','Connections'] as const;
export default function Corporate(){
 const [section,setSection]=useState<typeof sections[number]>('Projects');
 const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<Snapshot|null>(null);
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState(false);
 const [projectName,setProjectName]=useState(''),[projectId,setProjectId]=useState(''),[title,setTitle]=useState(''),[objective,setObjective]=useState(''),[acceptance,setAcceptance]=useState('');
 const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[confirmed,setConfirmed]=useState<Record<string,boolean>>({});
 const fail=(e:unknown)=>{setError(e instanceof ApiError && e.status===409?'Action blocked. Check owner provisioning, matching approval, schema and zero-cost constraints.':e instanceof Error?e.message:'Local request failed.');if(e instanceof ApiError && e.status===401){setSession(null);setData(null);}};
 async function refresh(){const snapshot=await api<Snapshot>('/api/corporate/snapshot');setData(snapshot);setProjectId(previous=>previous||snapshot.projects[0]?.id||'');}
 useEffect(()=>{let active=true;(async()=>{try{const config=await api<{mode:string;credential_login:boolean}>('/api/auth/config');if(!active)return;if(config.mode!=='production'||!config.credential_login){setError('Corporate requires provisioned credential authentication. The demo is separate.');return;}setEnabled(true);const s=await api<Session>('/api/auth/me');if(!active)return;setSession(s);await refresh();}catch(e){if(active && !(e instanceof ApiError && e.status===401))fail(e);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 async function perform(action:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(message);}catch(e){fail(e);}finally{setBusy(false);}}
 async function login(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const s=await api<Session>('/api/auth/login',undefined,{username,password});setSession(s);await refresh();}catch(e){fail(e);}finally{setPassword('');setBusy(false);}}
 async function logout(){setBusy(true);try{await api('/api/auth/logout',session?.csrf_token,{});setSession(null);setData(null);setConfirmed({});}catch(e){fail(e);}finally{setBusy(false);}}
 const post=(path:string,body:unknown)=>api(path,session?.csrf_token,body);
 return <div className="corp-shell"><header className="corp-header"><div><strong>ME Astro Fast</strong><span>Corporate · solo owner workspace</span></div><a href="/">Open separate demo</a>{session&&<button onClick={logout} disabled={busy}>Sign out</button>}</header>
 <main><h1>Produce quality work, deliberately.</h1><p>One owner. Durable decisions. No unattended factory execution.</p>
 {error&&<p role="alert" className="corp-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Saving local records…</p>}
 {loading?<p role="status">Checking protected workspace…</p>:!session?enabled?<form onSubmit={login} className="corp-form"><h2>Owner sign in</h2><label>Username<input required autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input required type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button></form>:null:<>
 <nav aria-label="Corporate sections">{sections.map(name=><button key={name} aria-current={section===name?'page':undefined} onClick={()=>{setSection(name);setNotice('');}}>{name}</button>)}</nav>
 {!data?<p>Corporate unavailable. Provision the designated owner and apply Corporate migrations locally.</p>:<section className="corp-panel"><h2>{section}</h2>
 {section==='Projects'&&<><p>Allowed repository: astro-dev-lab/me-fastapi · ID 1109489408</p><form className="corp-form" onSubmit={e=>{e.preventDefault();void perform(async()=>{await post('/api/corporate/projects',{name:projectName});setProjectName('');},'Project recorded.');}}><label>Project name<input required maxLength={80} value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button disabled={busy}>Add project</button></form><ul>{data.projects.map(p=><li key={p.id}><strong>{p.name}</strong> · {p.repository_name}</li>)}</ul></>}
 {section==='New Work'&&<><p>Submitting records an intake only. It does not approve, create a GitHub issue, or start a bot. Never include secrets.</p><form className="corp-form" onSubmit={e=>{e.preventDefault();void perform(async()=>{await post('/api/corporate/work',{project_id:projectId,request_key:requestKey,title,objective,acceptance});setRequestKey(crypto.randomUUID());setTitle('');setObjective('');setAcceptance('');},'Intake saved. Review and approve it separately.');}}><label>Project<select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose project</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Objective<textarea required maxLength={1000} value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>Acceptance criteria<textarea required maxLength={1000} value={acceptance} onChange={e=>setAcceptance(e.target.value)}/></label><button disabled={busy||!projectId}>Submit intake</button></form></>}
 {section==='Jobs'&&<><p>Contract jobs are local records. Actual Foreman dispatch remains BLOCKED.</p>{data.work.filter(w=>data.approvals.some(a=>a.work_id===w.id&&Date.parse(a.expires_at)>Date.now())&&!data.jobs.some(j=>j.work_id===w.id)).map(w=><article key={w.id}><h3>{w.title}</h3><button disabled={busy} onClick={()=>void perform(()=>post(`/api/corporate/work/${w.id}/dispatch-contract`,{reserve_cents:0}),'Contract reservation recorded; live dispatch remains blocked.')}>Prepare zero-cost contract</button></article>)}{data.jobs.map(j=><article key={j.id}><strong>{j.status}</strong><p>{j.issue_reference} · not a GitHub issue</p></article>)}{data.jobs.length===0&&<p>No contract jobs recorded.</p>}</>}
 {section==='Review/Approve'&&<><p>You may approve your own request deliberately. Bot builders and reviewers cannot approve.</p>{data.work.map(w=><article key={w.id}><h3>{w.title}</h3><p>{w.objective}</p><p><strong>Acceptance:</strong> {w.acceptance}</p><code className="corp-digest">{w.digest}</code>{data.approvals.some(a=>a.work_id===w.id)?<p>{data.approvals.some(a=>a.work_id===w.id&&Date.parse(a.expires_at)>Date.now())?'Owner approval recorded (24-hour contract authorization).':'Approval expired. Submit a new intake and deliberately approve it; old work remains immutable.'}</p>:<><label className="corp-check"><input type="checkbox" checked={!!confirmed[w.id]} onChange={e=>setConfirmed({...confirmed,[w.id]:e.target.checked})}/>I reviewed this exact request and approve a $0 contract test only. Live dispatch remains blocked.</label><button disabled={busy||!confirmed[w.id]} onClick={()=>void perform(async()=>{await post(`/api/corporate/work/${w.id}/approve`,{digest:w.digest,confirmation:'APPROVE_ZERO_COST_CONTRACT'});setConfirmed({...confirmed,[w.id]:false});},'Distinct owner approval recorded.')}>Approve zero-cost contract</button></>}</article>)}{data.work.length===0&&<p>No work awaiting review.</p>}<details><summary>Immutable audit history</summary><ol>{data.audit.map(a=><li key={a.id}>{a.event} · {new Date(a.created_at).toLocaleString()}</li>)}</ol></details></>}
 {section==='Costs'&&<><p>Incremental budget: $0.00 · USD</p><p>Reserved ${(data.costs.reserved_cents/100).toFixed(2)} · Recorded actual ${(data.costs.actual_cents/100).toFixed(2)}</p><p>This ledger is scoped to G2 contract operations. It is not a provider bill reconciliation.</p>{data.jobs.filter(j=>!data.costs.actuals.some(a=>a.job_id===j.id)).map(j=><button key={j.id} disabled={busy} onClick={()=>void perform(()=>post(`/api/corporate/jobs/${j.id}/actual`,{cents:0,reference:`contract_${j.id}`}), 'Zero-cost contract actual recorded.')}>Record $0 contract actual · {j.issue_reference}</button>)}</>}
 {section==='Connections'&&<><p>{data.connections.repository.name}</p><p>Contract adapter only · {data.connections.live_dispatch}</p><p>Foreman’s upstream raw label trigger must enforce owner authorization before live work is enabled. No credentials or arbitrary repository URLs are stored here.</p></>}
 </section>}</>}
 </main><footer>G2 · single repository pilot · no paid operations · no automatic merge or deploy</footer></div>;
}
